### ISSUE TITLE
PopUp with EU cookie does not appear - Backdrop 1.2.3

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/eu_cookie_compliance#1]
Hello Developers,

I use this EU Cookie modules and I have a problem, so the blog frontend no pop for the cookies appear.

I just deleted everything again browser cookies when Google Chrome browser and the problem persists.

I can let you get my login information for http://wpzweinull.ch/cms/backdrop also via mail. Maybe it's my settings of the module.

**Comment by Graham-72** [comment]
@AlexL777 I am investigating this. The module was working last month with previous version of Backdrop but there does seem to be a problem now. I see that it is not linking the javascript file eu_cookie_compliance.js to your home page. Have you got a file eu_cookie_config.settings.json in your config folder files/config..../active? - the installation procedure should have put it there.

**Comment by ghost** [comment]
I have the cookie module reinstalled and checked in my hand, what is mentioned directory. 

There, this file can be found: **eu_cookie_compliance.settings.json**

Otherwise no pop will be displayed in the frontend. The browser cookies also deleted again.

Is it perhaps my Backdrop Theme?

**Comment by Graham-72** [comment]
@AlexL777 I think I can see what is wrong with the module and I am working on a fix which should be done this weekend. I don't think it is your theme.

**Comment by ghost** [comment]
Ok, thanks, I'm waiting for the fix

**Comment by Graham-72** [comment]
@AlexL777 I have committed changes to three files. Please download these from the repo and try them. They are working on my test site. I would welcome any feedback from you so we can improve the module. I will wait to hear from you before making a new release - which will be 1.x-2.1.1

**Comment by ghost** [comment]
Thank you you could report so quickly. It has now also works with me, as you can see on this screenshot. Everything great! Thank you!

Now I'm going to translate only the texts in German and it is then properly fit for me.

![eu-cookies-backdrop-cms-all-right](https://cloud.githubusercontent.com/assets/7885632/12371633/7b792a40-bc39-11e5-9866-8e389bb49af5.jpg)

**Comment by ghost** [comment]
Even a little thing I have discovered. The popup can not hide after having accepted the cookies. I tried just the browser Firefox.

**Comment by Graham-72** [comment]
Was this after you clicked on a page or after clicking on the hide button? For me, also with Firefox, it is only hiding when I click on the hide button. I will investigate.

**Comment by ghost** [comment]
Now I have it. I can now also clearing the popup. With me in the Module settings the domain was registered, so it did not go.

But now I have the problem that the permissions you can not activate at Backdrop 1.3.0. I have to once again create an Issue.

In the permissions but these checkboxes and these can not activate it. I've just updated to 1.3.0 Backdrop.

**Comment by Graham-72** [comment]
I will look at this permissions issue. I, too, am now using 1.3.0  :+1:

**Comment by ghost** [comment]
The Permission Issue is online - in the Backdrop Issues. Cool, Backdrop 1.3.0 is already good, but I have some questions that need to be clarified yet. Otherwise, I like to work with the new version :smile:

**Comment by Graham-72** [comment]
I have replied to your issue at https://github.com/backdrop/backdrop-issues/issues/1540.

**Comment by davidvina** [comment]
I had the same problem, PopUp doesn't appear.
For correct this I changed the hook (on line 28 on eu_cookie_compliance_module file)
_eu_cookie_compliance_page_build(&$page)_
by
_eu_cookie_compliance_preprocess_page(&$page)_

an it works!

This is because hook_page_build(&$page) is not supported on new versions.  Here I found the explanation about that:
https://api.backdropcms.org/node/26861

sorry for my poor english!

**Comment by Graham-72** [comment]
@davidvina Thank you for reporting this but it is fixed in commit cba156f22fa1d57351103ed185f938f25015e0db

Perhaps you were installing Release 2.1.0 ? I must make a new release with the more recent commits which include the fix you have identified.

Release 2.1.1 just published. Is this OK?

**Comment by Graham-72** [comment]
I am closing this because we are now recommending release 1.x-1.26.0 and its successors for this module and abandoning the 1.x-2.1 branch.
