### ISSUE TITLE
Notes on the latest release

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/eu_cookie_compliance#11]
This is primarily for @Graham-72 so that when he gets back to this module he'll know what I've done, and why.

There was a [critical security release for the D7 version of eu_cookie_compliance](https://www.drupal.org/sa-contrib-2019-033) today.

Since the Backdrop Security Team was unable to reach this project's maintainers within a few hours, we stepped in to take care of [the fix](https://backdropcms.org/security/backdrop-sa-contrib-2019-004) for the Backdrop version of the module. That is, after all, what we're here for :)

While I was working on the fix, I noticed that the Backdrop version of the module was based off the (mostly abandoned) 2.x branch of the Drupal module. Most activity in Drupal is still happening on the 1.x branch, and the most recent commit to the 2.x branch was a merge of all the stuff that has been happening to 1.x.

In order to get all the improvements from the 1.x branch into this project, I thought the fastest approach would be to start the port over from the 1.x branch (using all the goodness in this current port) and then provide an "upgrade path" to get all the settings back in sync.

The old version of the port is preserved on the 1.x-2.1.x branch, while the newer version is now on the 1.x-2.x branch. Hopefully this will allow maintainers to move forward as usual, but keep the old code nearby, incase anything was overlooked.

Because the backdrop module version was already on 2.x, but the most recent release for Drupal 7 was numbered 1.26, **I numbered the latest release 1.x-2.26.0**. 

I was hoping that people would be able to tell that the 2.26.x version(s) of the Backdrop module matched the 1.26 version of the Drupal module -- without breaking the updater.

@Graham-72 let me know if you have any questions!

**Comment by Graham-72** [comment]
@jenlampton thank you very much for your work on this. I was away on holiday at the time and blissfully unaware of this happening! I now need to become familiar with the workings of this new version.
