### ISSUE TITLE
Need to review and incorporate D7 module updates.

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/eu_cookie_compliance#3]
Looking at the history of this port to Backdrop the most recent commit included in the originally ported D7 module was in November 2014 and there have been many changes since then. The current D7 release is 7.x-1.23 whereas this port was based on 7.x-1.14 with a few additional commits included.

**Comment by jenlampton** [comment]
I have a PR for this up at https://github.com/backdrop-contrib/eu_cookie_compliance/pull/9
